// src/views/CourseView.svelte
<script>
  import { getActiveTab, sendEvent } from "../helpers.js"

  let activeTab = null
  let loading = true
  let numberOfResources = 0
  let nDocuments = 0
  let nFolders = 0
  let documentsCb = null
  let foldersCb = null
  let downloadButton = null

  let useMoodleFilenameCb = null
  let prependCourseToFilenameCb = null
  let prependCourseShortcutToFilenameCb = null

  function scanForDocuments() {
    browser.tabs.sendMessage(activeTab.id, {
      command: "scan",
    })
    // .catch(showErrorContent)
  }

  function onDownload() {
    sendEvent("download")
    downloadButton.disabled = true
    browser.tabs.sendMessage(activeTab.id, {
      command: "crawl",
      useMoodleFilename: useMoodleFilenameCb.checked,
      prependCourseToFilename: prependCourseToFilenameCb.checked,
      prependCourseShortcutToFilename: prependCourseShortcutToFilenameCb.checked,
      skipDocuments: !documentsCb.checked,
      skipFolders: !foldersCb.checked,
    })
  }

  function onDocumentCbClick(e) {
    if (!e.target.checked && !foldersCb.checked) {
      downloadButton.disabled = true
    } else {
      downloadButton.disabled = false
    }
  }

  function onFolderCbClick() {
    if (!e.target.checked && !documentsCb.checked) {
      downloadButton.disabled = true
    } else {
      downloadButton.disabled = false
    }
  }

  browser.runtime.onMessage.addListener(message => {
    if (message.command === "scan-result") {
      numberOfResources = message.numberOfResources
      nDocuments = message.nDocuments
      nFolders = message.nFolders

      if (message.numberOfResources === 0) {
        downloadButton.disabled = true
      }

      if (message.nDocuments === 0) {
        documentsCb.disabled = true
        documentsCb.checked = false
      }

      if (message.nFolders === 0) {
        foldersCb.disabled = true
        foldersCb.checked = false
      }

      loading = false
    }
  })

  getActiveTab().then(tab => {
    activeTab = tab
    scanForDocuments()
  })
</script>

<style>
  .download-button {
    width: 100px;
    padding: 10px 0px;
    margin-top: 10px;
    border-radius: 5px;
    border: 0;
    background-color: #c50e20;
    color: white;
    font-weight: bold;
    text-align: center;
    letter-spacing: 0.5px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
  }

  .download-button:hover {
    cursor: pointer;
    text-decoration: underline;
  }

  .download-button:disabled {
    background-color: #a8a8a8;
    cursor: default;
    text-decoration: none;
  }

  .resource-info {
    margin-bottom: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .resource-info-number {
    font-weight: 600;
  }

  .resource-selection {
    margin-top: 10px;
  }

  .download-info {
    width: 300px;
    text-align: center;
    margin-bottom: 20px;
  }

  .checkbox-label {
    margin-left: 5px;
  }
</style>

<div class="resource-info">
  <div>
    There
    {#if numberOfResources === 1}is{:else}are{/if}
    <span class="resource-info-number">{numberOfResources}</span>
    {#if numberOfResources === 1}resource{:else}resources{/if}
    available for download.
  </div>
  <div class="resource-selection">
    <div>
      <label id="documents-cb-label">
        <input type="checkbox" bind:this={documentsCb} on:input={onDocumentCbClick} checked />
        <span class="checkbox-label">{nDocuments} document(s) (PDF, etc.)</span>
      </label>
    </div>
    <div>
      <label id="folders-cb-label">
        <input type="checkbox" bind:this={foldersCb} on:input={onFolderCbClick} checked />
        <span class="checkbox-label">{nFolders} folder(s)</span>
      </label>
    </div>
  </div>
</div>

<div class="download-info">
  Click the button below to download all available resources from this Moodle course.
</div>

<div>
  <div>
    <label>
      <input type="checkbox" bind:this={useMoodleFilenameCb} />
      <span class="checkbox-label">Use Moodle file name as actual file name</span>
    </label>
  </div>
  <div>
    <label>
      <input type="checkbox" bind:this={prependCourseShortcutToFilenameCb} />
      <span class="checkbox-label">Prepend course shortcut to each file name</span>
    </label>
  </div>
  <div>
    <label>
      <input type="checkbox" bind:this={prependCourseToFilenameCb} />
      <span class="checkbox-label">Prepend course name to each file name</span>
    </label>
  </div>
</div>
<button class="download-button" on:click={onDownload} bind:this={downloadButton}>Download</button>

// extension/src/views/CourseView.vue
<template>
  <div class="content-container">
    <div class="resource-info">
      <div>
        There
        <span v-if="nResources === 1">is</span>
        <span v-else>are</span>
        <span class="bold">{{ nResources }}</span>
        <span v-if="nResources === 1">resource</span>
        <span v-else>resources</span>
        available for download
      </div>
      <div v-if="showNewResourceInfo" class="new-resources-info">
        <div>
          Since last download
          <span class="bold">{{ nNewResources }} new</span>
          <span v-if="nNewResources === 1">resource</span>
          <span v-else>resources</span>
          <span v-if="nNewResources === 1">was</span>
          <span v-else>were</span> added
        </div>
        <div>
          <label>
            <input type="checkbox" ref="newResourceCb" @input="onNewResourceCbClick" />
            <span class="checkbox-label">Download only new resources</span>
          </label>
        </div>
      </div>
      <div class="resource-selection">
        <div>
          <label id="documents-cb-label">
            <input type="checkbox" ref="documentsCb" @input="onDocumentCbClick" checked />
            <span class="checkbox-label">
              <span v-if="onlyNewResources">{{ nNewDocuments }}</span>
              <span v-else>{{ nDocuments }}</span>
              document(s) (PDF, etc.)
            </span>
          </label>
        </div>
        <div>
          <label id="folders-cb-label">
            <input type="checkbox" ref="foldersCb" @input="onFolderCbClick" checked />
            <span class="checkbox-label">
              <span v-if="onlyNewResources">{{ nNewFolders }}</span>
              <span v-else>{{ nFolders }}</span>
              folder(s)
            </span>
          </label>
        </div>
      </div>
    </div>

    <!-- <div class="download-info">
      Click the button below to download all available resources from this Moodle course
    </div>-->

    <div>
      <div>
        <label>
          <input type="checkbox" ref="useMoodleFilenameCb" />
          <span class="checkbox-label">Use Moodle file name as actual file name</span>
        </label>
      </div>
      <div>
        <label>
          <input type="checkbox" ref="prependCourseShortcutToFilenameCb" />
          <span class="checkbox-label">Prepend course shortcut to each file name</span>
        </label>
      </div>
      <div>
        <label>
          <input type="checkbox" ref="prependCourseToFilenameCb" />
          <span class="checkbox-label">Prepend course name to each file name</span>
        </label>
      </div>
    </div>
    <button class="download-button" @click="onDownload" ref="downloadButton">Download</button>
  </div>
</template>

<script>
import { sendEvent, getActiveTab } from "../../shared/helpers.js"

export default {
  props: {
    activeTab: Object,
  },
  data: function() {
    return {
      loading: true,
      nDocuments: 0,
      nNewDocuments: 0,
      nFolders: 0,
      nNewFolders: 0,
      firstDownload: true,
      onlyNewResources: false,
    }
  },
  computed: {
    showNewResourceInfo: function() {
      return !this.firstDownload && (this.nNewDocuments > 0 || this.nNewFolders > 0)
    },
    nResources: function() {
      return this.nDocuments + this.nFolders
    },
    nNewResources: function() {
      return this.nNewDocuments + this.nNewFolders
    },
  },
  methods: {
    onDownload: function() {
      sendEvent("download")
      this.$refs.downloadButton.disabled = true
      browser.tabs.sendMessage(this.activeTab.id, {
        command: "crawl",
        useMoodleFilename: this.$refs.useMoodleFilenameCb.checked,
        prependCourseToFilename: this.$refs.prependCourseToFilenameCb.checked,
        prependCourseShortcutToFilename: this.$refs.prependCourseShortcutToFilenameCb.checked,
        skipDocuments: !this.$refs.documentsCb.checked,
        skipFolders: !this.$refs.foldersCb.checked,
        onlyNewResources: this.onlyNewResources,
      })
    },
    onDocumentCbClick: function(e) {
      if (!e.target.checked && !this.$refs.foldersCb.checked) {
        this.$refs.downloadButton.disabled = true
      } else {
        this.$refs.downloadButton.disabled = false
      }
    },
    onFolderCbClick: function(e) {
      if (!e.target.checked && !this.$refs.documentsCb.checked) {
        this.$refs.downloadButton.disabled = true
      } else {
        this.$refs.downloadButton.disabled = false
      }
    },
    onNewResourceCbClick: function(e) {
      this.onlyNewResources = this.$refs.newResourceCb.checked

      if (this.onlyNewResources) {
        if (this.nNewDocuments === 0) {
          this.$refs.documentsCb.disabled = true
          this.$refs.documentsCb.checked = false
        } else {
          this.$refs.documentsCb.disabled = false
          this.$refs.documentsCb.checked = true
        }

        if (this.nNewFolders === 0) {
          this.$refs.foldersCb.disabled = true
          this.$refs.foldersCb.checked = false
        } else {
          this.$refs.foldersCb.disabled = false
          this.$refs.foldersCb.checked = true
        }
      } else {
        if (this.nDocuments === 0) {
          this.$refs.documentsCb.disabled = true
          this.$refs.documentsCb.checked = false
        } else {
          this.$refs.documentsCb.disabled = false
          this.$refs.documentsCb.checked = true
        }

        if (this.nFolders === 0) {
          this.$refs.foldersCb.disabled = true
          this.$refs.foldersCb.checked = false
        } else {
          this.$refs.foldersCb.disabled = false
          this.$refs.foldersCb.checked = true
        }
      }

      this.$refs.downloadButton.disabled = false
    },
  },
  created: function() {
    // browser.storage.local.get(this.activeTab.url).then(res => {
    //   this.firstDownload = !res[this.activeTab.url]
    // })
  },
  mounted: function() {
    browser.runtime.onMessage.addListener(message => {
      if (message.command === "scan-result") {
        this.nDocuments = message.nDocuments
        this.nNewDocuments = message.nNewDocuments
        this.nFolders = message.nFolders
        this.nNewFolders = message.nNewFolders

        if (this.nResources === 0) {
          this.$refs.downloadButton.disabled = true
        }

        if (this.nDocuments === 0) {
          this.$refs.documentsCb.disabled = true
          this.$refs.documentsCb.checked = false
        }

        if (this.nFolders === 0) {
          this.$refs.foldersCb.disabled = true
          this.$refs.foldersCb.checked = false
        }

        this.loading = false
      }
    })

    // Scan for documents
    browser.tabs.sendMessage(this.activeTab.id, {
      command: "scan",
    })
  },
}
</script>

<style scoped>
.download-button {
  width: 100px;
  padding: 10px 0px;
  margin-top: 10px;
  border-radius: 5px;
  border: 0;
  background-color: #c50e20;
  color: white;
  font-weight: bold;
  text-align: center;
  letter-spacing: 0.5px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
}

.download-button:hover {
  cursor: pointer;
  text-decoration: underline;
}

.download-button:disabled {
  background-color: #a8a8a8;
  cursor: default;
  text-decoration: none;
}

.resource-info {
  margin-bottom: 20px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.bold {
  font-weight: 600;
}

.new-resources-info {
  margin-top: 10px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.resource-selection {
  margin-top: 10px;
}

.download-info {
  width: 300px;
  text-align: center;
  margin-bottom: 20px;
}

.checkbox-label {
  margin-left: 5px;
}
</style>
